name: Run Unit Tests

on:
  push:
    branches:
      - test   
      - dev    
  pull_request:
    branches:
      - dev
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
   
      - name: Install dependencies
        run: npm install
        working-directory: 07-Conference-Ticket-Generator
      
      - name: Run unit tests
        run: npm test
        working-directory: 07-Conference-Ticket-Generator
